matrix:
  include:
    - language: python
      python: 2.7
      env: TOXENV=py27-cmake-serial-codecov BUILDS=Sbuild
    - language: python
      python: 2.7
      env: TOXENV=py27-cmake-mpi-nodes1-codecov BUILDS=Mbuild
    - language: python
      python: 2.7
      env: TOXENV=py27-cmake-mpi-nodes2 BUILDS=Mbuild
    - language: python
      python: 2.7
      env: TOXENV=py27-pip-serial BUILDS=
    - language: generic
      os: osx
      env: TOXENV=py36-cmake-mpi-nodes2 BUILDS=Mbuild
    - language: generic
      os: osx
      env: TOXENV=py36-pip-serial BUILDS=
    - language: python
      python: 3.6
      stage: deploy
      env: TOXENV=docs BUILDS=
      addons:
        apt:
          packages:
            - doxygen
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - mpi-default-dev
      - mpi-default-bin
      - libscalapack-mpi-dev
install: .travis/install.sh
script:
  - 'make test && { [[ $TOXENV != docs ]] || make doc; }'
  - tox
after_success: .travis/after-success.sh
notifications:
  pushover:
    api_key:
      secure: Z1rNy7duOeLxsmtuPVTf7Z/qySXVuKjxxNnQeDWiMCR151yHFXB8RMP9riv0z0yK+5q68FOfv9vcfnWXRws6g/lYZUjTcwWxH11gu3rzP9s0dGpmlNTmpr0/mbPQGWF13bJDSYE4HNPNmU9fGwD7YgXxexdHWROtY7nveKctpbl/ZC+vAPa/uSSVboyJsl4tUwcosGcROvo7G8ZveO6upLoSfpeEQXPRQ2rDMMILXz7PKAqhkm1wPytLeZMn3OLviQH+Y46PmK7wA/ZoO47k8iCzdQVpuGE+TPmo+4N5pKSdKXl1PfC7HlVvoltlKWeaTCjH8PXgViVcMNDA8qTwwc4gTepLAJoOlozxGIRs5i+ks+kHCM50dg4y3lneRKosDTAo2yPvxuGBkQ8/Vc98q5iTauTtAehKLf3rDoSfsRxYSiDgng3ajPJEebUwH3Gy3fUS8nWs4NOZ5aWGE8BtOCdfAxCg34A8IfYYPiZDfruTmv25UmDbXjzO2V+RNp+ekI5Gu8DDEf1yYdwSVqJYxHzF8CMd8CcsJdbwWJ0u5OwPkXNfAsyf0+k9j2ypT4iQ6S+gteGMPNRnWZtzDSe7agmgXzlT2UmltjV57QvKTRMjxNVZO6DOy+j1iX6TVZ63WIepPc3nfEphiiVKcbW5sSmx8iSloqUO014OwZGAMsA=
    users:
      secure: bPizpayT/DYyIXdJYlqPBEevcMCIgzikIyjeIF31oYszutC4KSsUCaLcywVYM3pKrotwlKZ4oThfFkBLg3lM6olc63/+BUI8/kIiiegFHrEiRZMG8nqRbharwhnYjnN/arEf3bziBKZIPLFs+bYQVkzwOF2DXg4sr13ggQymeoJYnDC8sAC23jzoBnsTJrXL4UpoB/08bgAbkUfqTb15hXsJ//aSPuJNMLmq6GOobUQLGn72ZAP6+LrVrgD+E+Tov7FRHon+6+GdUkNoZ8+zz1O9fEx8P4cpiDt0aFLr76O5/Zy1sjEM2o8zatLCMVYILEhLoIg5cVp0MsySEbitW39l+xMf1WOu7bPXb9b1xKLE4sKozlEhueBriE7EN6hE+pWWWS7mMNEe+qVOZWDk9vXhEIKHCU07scbBAMNy1bDysegLbQU1UT6qbHi3TP5HK7zsRRHnt0mA047/NA5CbJ/V+XO1wZVqZccgZCt1Ao22V88YZXvW9tQgSgXs1TBRdlK+a5jvM8JzvSn0DPs83PC3KwvBZysTtlzjHKt7Ccr13id3MpsmCFxD4hV7xxprKyFy/MzDCYpK7eRTGARdcKSLY26W8yJadJe64WqSN+JmAI6vuQLPHP3SKDc9GbozyW/Z6GeMF504KYa5ctDSE1PMHlfrIoUGSoY+/J1wLJs=
